version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Release Notes
#          command: echo "#BRANCH: $CIRCLE_BRANCH" > "release-notes.txt"
#          command: echo "#CHANGELOG" >> "release-notes.txt"
          command: git log origin/dev..origin/$CIRCLE_BRANCH --no-merges --pretty=format:"%h %s" >> "release-notes.txt"
  staging:
    - run:
        name: Staging
        command: ./gradlew :app:clean :app:assembleStagingDebug :app:crashlyticsUploadDistributionStagingDebug
        no_output_timeout: 10m
  prod:
    - run:
        name: Production
        command: ./gradlew :app:clean :app:assembleProdRelease :app:crashlyticsUploadDistributionProdRelease
        no_output_timeout: 15m
  save:
    requires:
      - staging
      - prod
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: release-notes.txt
          destination: reports
workflows:
  version: 2
  build_and_distribute:
    jobs:
      - prod
      - staging
