version: 2
aliases:
  docker_build_config: &docker_build_config
    docker:
      - image: circleci/android:api-27-alpha
  build_deploy_steps: &build_deploy_steps
    steps:
      - restore_cache:
          keys:
            - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - jars-
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Release Notes
          command: |
            echo "#BRANCH: ${CIRCLE_BRANCH}" > "release-notes.txt"
            echo "#CHANGELOG" >> "release-notes.txt"
            git log origin/dev..origin/${CIRCLE_BRANCH} --no-merges --pretty=format:"%h %s" >> "release-notes.txt"
      - run:
          name: Build
          command: |
            # ASSEMBLE_ENV and DIST_ENV are defined in circleci context via worflows
            ./gradlew :app:clean :app:assemble${ASSEMBLE_ENV} :app:crashlyticsUploadDistribution${DIST_ENV}
          no_output_timeout: 10m
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: release-notes.txt
          destination: reports
jobs:
  build_staging:
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
    <<: *docker_build_config
    <<: *build_deploy_steps
  build_production:
    working_directory: ~/code
    environment:
      JVM_OPTS: -Xmx3200m
    <<: *docker_build_config
    <<: *build_deploy_steps
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_staging:
          context: android-staging
          filters:
            branches:
              ignore:
                - master
      - build_production:
          context: android-production
          filters:
            branches:
              only:
                - master
