package com.mobile.responses

enum class SubscriptionStatus {
    ACTIVE,
    ACTIVE_FREE_TRIAL,
    ADMIN_REVIEWED,
    BROKEN,
    CANCELLED,
    CANCELLED_PAST_DUE,
    ENDED_FREE_TRIAL,
    EXPIRED,
    FREE_TRIAL_PAYMENT_DECLINED,
    MIGRATED,
    MIGRATION_FAILED,
    MISSING,
    PAST_DUE,
    PENDING_ACTIVATION,
    PENDING_CHARGE,
    PENDING_FREE_TRIAL,
    RESTARTED_FREE_TRIAL,
    UNKNOWN
}