package com.mobile.profile

enum class Profile {
    ACCOUNT_DETAILS,
    ACCOUNT_INFORMATION,
    CHANGE_PASSWORD,
    CURRENT_RESERVATION,
    CAPPED_PLAN,
    HISTORY,
    REFER_A_FRIEND,
    LOYALTY_PROGRAMS,
    HOW_TO_USE_MOVIEPASS,
    HELP,
    NOTIFICATIONS,
    PEAK_PASS,
    PLAN_AND_BILLING,
    LINK,
    SIGN_OUT,
    SHIPPING_ADDRESS,
    VERSION,
    CLEAR_FLAGS,
    DIVIDER
}